name = "agenl"
version = "0.1.0"
defaultTargets = ["AGENL", "Proofs"]

[[lean_lib]]
name = "AGENL"
globs = ["AGENL.+"]

[[lean_lib]]
name = "Proofs"
globs = ["proofs.orbital.+"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.29.0"
